version: "3"

services:
  main_bot:
    build:
      context: .
      dockerfile: dockerfile

    env_file:
      - .env

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}


    command: ["redis-server", "--appendonly", "yes", "--requirepass", 'echo \"$REDIS_PASSWORD\"']




volumes:
  redis_data:
