version: "3"

services:
  main_bot:
    build:
      context: .
      dockerfile: dockerfile

    env_file:
      - .env

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    restart: always
    command: [
      "bash", "-c",
      '
      docker-entrypoint.sh
      --appendonly yes
      --requirepass ${REDIS_PASSWORD}
      '
    ]


volumes:
  redis_data:
